# Copyright 2020 Adobe
# All Rights Reserved.

# NOTICE: Adobe permits you to use, modify, and distribute this file in
# accordance with the terms of the Adobe license agreement accompanying
# it. If you have received this file from a source other than Adobe,
# then your use, modification, or distribution of it requires the prior
# written permission of Adobe.

language: node_js
os:
  - linux

node_js:
  - "10.15"
  - "10.19"
  - "12"
  - "14"

install:
  - npm version
  - npm install
jobs:
  include:
    - stage: Test
      script: npm test
    - stage: release
      if: branch = master
      node_js: "12"
      script: skip
      before_deploy:
        - "echo 'semantic release...'"
      deploy:
        on:
          branch: master
          condition:  $TRAVIS_OS_NAME = linux
        provider: script
        skip_cleanup: true
        script: npx semantic-release --debug

after_success:
  - npm run report-coverage
