version: 2
workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm test -- -v
      - run: npm run report-coverage
      - store_test_results:
          path: test-results
